# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


0="${ZERO:-${${0:#$ZSH_ARGZERO}:-${(%):-%N}}}"
0="${${(M)0:#/*}:-$PWD/$0}"
fpath+="${0:A:h}/completions"


alias k='kubectl'
alias ksys='kubectl --namespace kube-system'
alias ka='kubectl apply --recursive -f'
alias kak='kubectl apply -k'
alias kk='kubectl kustomize'

function kex() {
  local fek() { echo "usage: kex requires at least two arguments" >&2; kubectl exec -i -t --help ; }
  [[ -z $# ]] || [[ $# > 1 ]] || { fek && return 1; }
  kubectl exec -i -t "${@:1:$# -1}" -- "${@: -1}"
}


function ksysex() {
  local fek() { echo "usage: ksysex requires at least two arguments" >&2; kubectl --namespace kube-system exec -i -t --help ; }
  [[ -z $# ]] || [[ $# > 1 ]] || { fek && return 1; }
  kubectl --namespace kube-system exec -i -t "${@:1:$# -1}" -- "${@: -1}"
}

alias ked='kubectl edit'
alias ksysed='kubectl --namespace kube-system edit'
alias kl='kubectl logs -f'
alias ksysl='kubectl --namespace kube-system logs -f'
alias klp='kubectl logs -f -p'
alias ksyslp='kubectl --namespace kube-system logs -f -p'
alias kg='kubectl get'
alias ksysg='kubectl --namespace kube-system get'
alias kd='kubectl describe'
alias ksysd='kubectl --namespace kube-system describe'
alias krm='kubectl delete'
alias ksysrm='kubectl --namespace kube-system delete'
alias krun='kubectl run --rm --restart Never --image-pull-policy IfNotPresent -i -t'
alias ksysrun='kubectl --namespace kube-system run --rm --restart Never --image-pull-policy IfNotPresent -i -t'
alias kedp='kubectl edit pods'
alias ksysedp='kubectl --namespace kube-system edit pods'
alias kgp='kubectl get pods'
alias ksysgp='kubectl --namespace kube-system get pods'
alias kdp='kubectl describe pods'
alias ksysdp='kubectl --namespace kube-system describe pods'
alias krmp='kubectl delete pods'
alias ksysrmp='kubectl --namespace kube-system delete pods'
alias kedj='kubectl edit jobs'
alias ksysedj='kubectl --namespace kube-system edit jobs'
alias kgj='kubectl get jobs'
alias ksysgj='kubectl --namespace kube-system get jobs'
alias kdj='kubectl describe jobs'
alias ksysdj='kubectl --namespace kube-system describe jobs'
alias krmj='kubectl delete jobs'
alias ksysrmj='kubectl --namespace kube-system delete jobs'
alias kedcj='kubectl edit cronjobs'
alias ksysedcj='kubectl --namespace kube-system edit cronjobs'
alias kgcj='kubectl get cronjobs'
alias ksysgcj='kubectl --namespace kube-system get cronjobs'
alias kdcj='kubectl describe cronjobs'
alias ksysdcj='kubectl --namespace kube-system describe cronjobs'
alias krmcj='kubectl delete cronjobs'
alias ksysrmcj='kubectl --namespace kube-system delete cronjobs'
alias kedd='kubectl edit deployment'
alias ksysedd='kubectl --namespace kube-system edit deployment'
alias kgd='kubectl get deployment'
alias ksysgd='kubectl --namespace kube-system get deployment'
alias kdd='kubectl describe deployment'
alias ksysdd='kubectl --namespace kube-system describe deployment'
alias krmd='kubectl delete deployment'
alias ksysrmd='kubectl --namespace kube-system delete deployment'
alias kedsts='kubectl edit statefulset'
alias ksysedsts='kubectl --namespace kube-system edit statefulset'
alias kgsts='kubectl get statefulset'
alias ksysgsts='kubectl --namespace kube-system get statefulset'
alias kdsts='kubectl describe statefulset'
alias ksysdsts='kubectl --namespace kube-system describe statefulset'
alias krmsts='kubectl delete statefulset'
alias ksysrmsts='kubectl --namespace kube-system delete statefulset'
alias kedsvc='kubectl edit service'
alias ksysedsvc='kubectl --namespace kube-system edit service'
alias kgsvc='kubectl get service'
alias ksysgsvc='kubectl --namespace kube-system get service'
alias kdsvc='kubectl describe service'
alias ksysdsvc='kubectl --namespace kube-system describe service'
alias krmsvc='kubectl delete service'
alias ksysrmsvc='kubectl --namespace kube-system delete service'
alias keding='kubectl edit ingress'
alias ksyseding='kubectl --namespace kube-system edit ingress'
alias kging='kubectl get ingress'
alias ksysging='kubectl --namespace kube-system get ingress'
alias kding='kubectl describe ingress'
alias ksysding='kubectl --namespace kube-system describe ingress'
alias krming='kubectl delete ingress'
alias ksysrming='kubectl --namespace kube-system delete ingress'
alias kedcm='kubectl edit configmap'
alias ksysedcm='kubectl --namespace kube-system edit configmap'
alias kgcm='kubectl get configmap'
alias ksysgcm='kubectl --namespace kube-system get configmap'
alias kdcm='kubectl describe configmap'
alias ksysdcm='kubectl --namespace kube-system describe configmap'
alias krmcm='kubectl delete configmap'
alias ksysrmcm='kubectl --namespace kube-system delete configmap'
alias kedsec='kubectl edit secret'
alias ksysedsec='kubectl --namespace kube-system edit secret'
alias kgsec='kubectl get secret'
alias ksysgsec='kubectl --namespace kube-system get secret'
alias kdsec='kubectl describe secret'
alias ksysdsec='kubectl --namespace kube-system describe secret'
alias krmsec='kubectl delete secret'
alias ksysrmsec='kubectl --namespace kube-system delete secret'
alias kgno='kubectl get nodes'
alias kdno='kubectl describe nodes'
alias kedns='kubectl edit namespaces'
alias kgns='kubectl get namespaces'
alias kdns='kubectl describe namespaces'
alias krmns='kubectl delete namespaces'
alias kge='kubectl get events'
alias ksysge='kubectl --namespace kube-system get events'
alias kgst='kubectl get --sort-by='.lastTimestamp''
alias ksysgst='kubectl --namespace kube-system get --sort-by='.lastTimestamp''
alias kgpst='kubectl get pods --sort-by='.lastTimestamp''
alias ksysgpst='kubectl --namespace kube-system get pods --sort-by='.lastTimestamp''
alias kgjst='kubectl get jobs --sort-by='.lastTimestamp''
alias ksysgjst='kubectl --namespace kube-system get jobs --sort-by='.lastTimestamp''
alias kgcjst='kubectl get cronjobs --sort-by='.lastTimestamp''
alias ksysgcjst='kubectl --namespace kube-system get cronjobs --sort-by='.lastTimestamp''
alias kgdst='kubectl get deployment --sort-by='.lastTimestamp''
alias ksysgdst='kubectl --namespace kube-system get deployment --sort-by='.lastTimestamp''
alias kgstsst='kubectl get statefulset --sort-by='.lastTimestamp''
alias ksysgstsst='kubectl --namespace kube-system get statefulset --sort-by='.lastTimestamp''
alias kgsvcst='kubectl get service --sort-by='.lastTimestamp''
alias ksysgsvcst='kubectl --namespace kube-system get service --sort-by='.lastTimestamp''
alias kgingst='kubectl get ingress --sort-by='.lastTimestamp''
alias ksysgingst='kubectl --namespace kube-system get ingress --sort-by='.lastTimestamp''
alias kgcmst='kubectl get configmap --sort-by='.lastTimestamp''
alias ksysgcmst='kubectl --namespace kube-system get configmap --sort-by='.lastTimestamp''
alias kgsecst='kubectl get secret --sort-by='.lastTimestamp''
alias ksysgsecst='kubectl --namespace kube-system get secret --sort-by='.lastTimestamp''
alias kgnost='kubectl get nodes --sort-by='.lastTimestamp''
alias kgnsst='kubectl get namespaces --sort-by='.lastTimestamp''
alias kgest='kubectl get events --sort-by='.lastTimestamp''
alias ksysgest='kubectl --namespace kube-system get events --sort-by='.lastTimestamp''
alias kedf='kubectl edit --recursive -f'
alias kgf='kubectl get --recursive -f'
alias kdf='kubectl describe --recursive -f'
alias krmf='kubectl delete --recursive -f'
alias kgstf='kubectl get --sort-by='.lastTimestamp' --recursive -f'

function kexn() {
  local fek() { echo "usage: kexn requires at least two arguments" >&2; kubectl exec -i -t --namespace --help ; }
  [[ -z $# ]] || [[ $# > 1 ]] || { fek && return 1; }
  kubectl exec -i -t --namespace "${@:1:$# -1}" -- "${@: -1}"
}

alias kedn='kubectl edit --namespace'
alias kln='kubectl logs -f --namespace'
alias kgn='kubectl get --namespace'
alias kdn='kubectl describe --namespace'
alias krmn='kubectl delete --namespace'
alias kedpn='kubectl edit pods --namespace'
alias kgpn='kubectl get pods --namespace'
alias kdpn='kubectl describe pods --namespace'
alias krmpn='kubectl delete pods --namespace'
alias kedjn='kubectl edit jobs --namespace'
alias kgjn='kubectl get jobs --namespace'
alias kdjn='kubectl describe jobs --namespace'
alias krmjn='kubectl delete jobs --namespace'
alias kedcjn='kubectl edit cronjobs --namespace'
alias kgcjn='kubectl get cronjobs --namespace'
alias kdcjn='kubectl describe cronjobs --namespace'
alias krmcjn='kubectl delete cronjobs --namespace'
alias keddn='kubectl edit deployment --namespace'
alias kgdn='kubectl get deployment --namespace'
alias kddn='kubectl describe deployment --namespace'
alias krmdn='kubectl delete deployment --namespace'
alias kedstsn='kubectl edit statefulset --namespace'
alias kgstsn='kubectl get statefulset --namespace'
alias kdstsn='kubectl describe statefulset --namespace'
alias krmstsn='kubectl delete statefulset --namespace'
alias kedsvcn='kubectl edit service --namespace'
alias kgsvcn='kubectl get service --namespace'
alias kdsvcn='kubectl describe service --namespace'
alias krmsvcn='kubectl delete service --namespace'
alias kedingn='kubectl edit ingress --namespace'
alias kgingn='kubectl get ingress --namespace'
alias kdingn='kubectl describe ingress --namespace'
alias krmingn='kubectl delete ingress --namespace'
alias kedcmn='kubectl edit configmap --namespace'
alias kgcmn='kubectl get configmap --namespace'
alias kdcmn='kubectl describe configmap --namespace'
alias krmcmn='kubectl delete configmap --namespace'
alias kedsecn='kubectl edit secret --namespace'
alias kgsecn='kubectl get secret --namespace'
alias kdsecn='kubectl describe secret --namespace'
alias krmsecn='kubectl delete secret --namespace'
alias kgen='kubectl get events --namespace'
alias kgstn='kubectl get --sort-by='.lastTimestamp' --namespace'
alias kgpstn='kubectl get pods --sort-by='.lastTimestamp' --namespace'
alias kgjstn='kubectl get jobs --sort-by='.lastTimestamp' --namespace'
alias kgcjstn='kubectl get cronjobs --sort-by='.lastTimestamp' --namespace'
alias kgdstn='kubectl get deployment --sort-by='.lastTimestamp' --namespace'
alias kgstsstn='kubectl get statefulset --sort-by='.lastTimestamp' --namespace'
alias kgsvcstn='kubectl get service --sort-by='.lastTimestamp' --namespace'
alias kgingstn='kubectl get ingress --sort-by='.lastTimestamp' --namespace'
alias kgcmstn='kubectl get configmap --sort-by='.lastTimestamp' --namespace'
alias kgsecstn='kubectl get secret --sort-by='.lastTimestamp' --namespace'
alias kgestn='kubectl get events --sort-by='.lastTimestamp' --namespace'
